name: CI

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

permissions: # This is required to allow the workflow to read PR comments
  pull-requests: read
  contents: read
  actions: read

jobs:
  types:
    name: Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'release/') }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Types
        run: npm run type-check

  