name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      release_notes: ${{ steps.release-notes.outputs.release_notes }}
      release_tag_name: ${{ steps.release-notes.outputs.release_tag_name }}
      release_published_at: ${{ steps.release-notes.outputs.release_published_at }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}